# Generated by Django 4.1.7 on 2023-02-15 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='date_hired',
            field=models.DateField(default=datetime.datetime(2023, 2, 15, 12, 17, 7, 250345, tzinfo=datetime.timezone.utc)),
        ),
    ]
