# Generated by Django 4.1.7 on 2023-02-15 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_alter_agent_date_hired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='date_hired',
            field=models.DateField(default=datetime.datetime(2023, 2, 15, 16, 22, 31, 295634, tzinfo=datetime.timezone.utc)),
        ),
    ]
